[tool.poetry]
name = "bayespec"
version = "0.0.1"
description = "A Python package designed for fitting astronomical X/Î³-ray spectra."
authors = ["xuewc <wcxuemail@gmail.com>"]
license = "GPLv3"
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.8, <3.12"
arviz = ">=0.15.1"
astropy = ">=5.2.2"
jax = ">=0.4.13"
numpy = "<=1.24.4"  # should be linked to veclib if platform_machine=='arm64'
numpyro = ">=0.12.1"
tqdm = ">=4.66.1"

# dev dependencies
jupyterlab = { version = ">=4.0.8", optional = true }

# test dependencies

# docs dependencies
sphinx = { version = ">=7.1.2", optional = true }
sphinx_rtd_theme = { version = ">=1.3.0", optional = true }
numpydoc = { version = ">=1.6.0", optional = true }

[tool.poetry.extras]
dev = ["jupyterlab"]
test = []
docs = ["sphinx", "sphinx_rtd_theme", "numpydoc"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
