[project]
name = "elisa-lib"
dynamic = ["version"]
description = "An efficient and fast library for spectral analysis in high-energy astrophysics."
readme = "README.md"
requires-python = ">=3.9, <3.12"
license = "GPL-3.0-or-later"
keywords = []
authors = [
    { name = "Wang-Chen Xue", email = "wcxuemail@gmail.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "arviz",
    "astropy",
    "corner>=2.2.2",
    "iminuit",
    "jax",
    "jaxns>=2.4.8",
    "numpy",
    "numpyro",
    "optimistix",
    "prettytable",
    "quadax @ git+https://github.com/f0uriest/quadax.git@640afd5bacc1a42f1e3c55c266fc5a02f668b2d1",
    "seaborn",
    "tinygp",
    "tqdm",
]


[project.optional-dependencies]
xspec = ["xspex"]
test = ["pytest", "pytest-cov", "coverage[toml]"]
docs = [
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-book-theme",
    "sphinx-copybutton",
    "sphinx-design",
    "myst-nb",
    "numpydoc",
]
dev = ["pre-commit>=3.6.0", "ruff>=2.0"]


[project.urls]
Documentation = "https://github.com/wcxve/elisa#readme"
Issues = "https://github.com/wcxve/elisa/issues"
Source = "https://github.com/wcxve/elisa"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch]
metadata.allow-direct-references = true
version.path = "src/elisa/__about__.py"
build.targets.wheel.packages = ["src/elisa"]

[[tool.hatch.envs.all.matrix]]
python = ["3.9", "3.10", "3.11"]

[tool.ruff]
line-length = 79
target-version = "py39"
extend-exclude = ["src/elisa/infer/nested_sampling.py"]
extend-include = ["*.ipynb"]
format.quote-style = "single"
lint.extend-select = ["Q"]
lint.flake8-quotes.inline-quotes = "single"
lint.ignore = [
    "B028",  # allow warnings without stacklevel
    "C901",  # allow functions with a high complexity
    "E731",  # allow lambda functions
]
lint.ignore-init-module-imports = true
lint.isort.known-first-party = ["elisa"]
lint.isort.combine-as-imports = true
lint.select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "UP",  # pyupgrade
]
lint.pydocstyle.convention = "numpy"

[tool.coverage.run]
parallel = true
branch = true
source = ["elisa"]
omit = [
    "docs/*",
    "tests/*",
    "*__init__*"
]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.report]
omit = ["src/elisa/infer/nested_sampling.py"]
show_missing = true
