[project]
name = "elisa-lib"
dynamic = ["version"]
description = "An efficient and fast library for spectral analysis in high-energy astrophysics."
readme = "README.md"
requires-python = ">=3.9, <3.12"
license = "GPL-3.0-or-later"
keywords = []
authors = [
    { name = "Wang-Chen Xue", email = "wcxuemail@gmail.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "arviz",
    "astropy",
    "corner>=2.2.2",
    "iminuit",
    "jax",
    "jaxns>=2.3.4",
    "jaxopt",
    "numpy",
#    "numpy<=1.24.4 ; sys_platform != 'darwin' or platform_machine != 'arm64'",
#    "numpy @ https://github.com/numpy/numpy/releases/download/v1.24.4/numpy-1.24.4.tar.gz ; sys_platform == 'darwin' and platform_machine == 'arm64'",
    "numpyro",
    "prettytable",
    "quadax @ git+https://github.com/f0uriest/quadax.git@640afd5bacc1a42f1e3c55c266fc5a02f668b2d1",
    "tinygp",
    "tqdm",
]


[project.optional-dependencies]
xspec = ["xspex"]
test = ["pytest", "pytest-cov", "coverage[toml]"]
docs = [
    "sphinx",
    "sphinx_rtd_theme",
    "numpydoc"
]
dev = ["pre-commit>=3.6.0", "ruff"]


[project.urls]
Documentation = "https://github.com/wcxve/elisa#readme"
Issues = "https://github.com/wcxve/elisa/issues"
Source = "https://github.com/wcxve/elisa"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch]
metadata.allow-direct-references = true
version.path = "src/elisa/__about__.py"
build.targets.wheel.packages = ["src/elisa"]

[[tool.hatch.envs.all.matrix]]
python = ["3.9", "3.10", "3.11"]

[tool.ruff]
format.quote-style = "single"
lint.pydocstyle.convention = "numpy"
target-version = "py39"
line-length = 79
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "UP",  # pyupgrade
]
ignore = [
    "B028",  # allow warnings without stacklevel
    "C901",  # allow functions with a high complexity
    "E731",  # allow lambda functions
]
ignore-init-module-imports = true
extend-select = ["Q"]
extend-include = ["*.ipynb"]
flake8-quotes.inline-quotes = "single"
isort.known-first-party = ["elisa"]
isort.combine-as-imports = true

[tool.ruff.lint.per-file-ignores]
"nested_sampling.py" = ["E501"]

[tool.coverage.run]
parallel = true
branch = true
source = ["elisa"]
omit = [
    "docs/*",
    "tests/*",
    "*__init__*"
]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.report]
show_missing = true
